name: flux_firebase
description: A Firebase package for FluxStore apps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fstore:
    path: ../../
  inspireui: 2.2.4

  # FIREBASE PACKAGES
  firebase_core: ^3.15.1
  firebase_analytics: ^11.3.2
  firebase_auth: ^5.6.2
  firebase_remote_config: ^5.4.7
  firebase_dynamic_links: ^6.1.9
  cloud_firestore: ^5.6.11
  share_plus: ^11.0.0

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: ^6.0.0
  firebase_analytics_platform_interface: ^4.4.2
  firebase_auth_platform_interface: ^7.7.2
  firebase_remote_config_platform_interface: ^1.5.7
  firebase_dynamic_links_platform_interface: ^0.2.7+9
  cloud_firestore_platform_interface: ^6.6.11
  firebase_messaging_platform_interface: ^4.6.9

  # PUSH NOTIFICATION
  firebase_messaging: ^15.2.9

  # OTHERS
  timeago: 3.7.0
  flutter_local_notifications: 18.0.1
  #  share: 2.0.4
  provider: ^6.1.2
  collection: any
  easy_debounce: 2.0.3
  app_links: ^6.4.0

flutter:
  uses-material-design: true

dependency_overrides:
  intl: ^0.18.0
  async: 2.13.0
