name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# Release version: v3.10.0 (Do not change this line)
# A version number is three numbers separated by dots, like 1.2.43 - followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion. Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  inspireui: 2.2.1

  flutterflow:
    path: packages/flutterflow/
  flux_firebase:
    path: packages/flux_firebase/

  # Base
  flutter_localization: ^0.1.11
  intl: ^0.19.0
  crypto: 3.0.5
  path_provider: 2.1.4
  url_launcher: 6.1.11
  flutter_secure_storage: 9.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 1.1.0
  http_auth: 1.0.3
  share: 2.0.4
  tuple: 2.0.1
  collection: any
  quiver: 3.2.1
  async: 2.11.0
  html: 0.15.3
  vector_math: 2.1.4
  path: 1.9.0
  flutter_svg: 2.0.7
  notification_permissions: 0.6.1
  flutter_local_notifications: 17.2.2
  onesignal_flutter: 3.5.1

  # STATE MANAGEMENT
  provider: 6.0.5
  get_it: 7.6.0

  # SPLASH SCREEN, ONBOARD
  lottie: 2.3.2
  rive: 0.11.16

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 4.2.2
  webview_flutter_web: 0.2.2+2
  flutter_inappwebview: 5.7.2+3

  # HTML render
  flutter_widget_from_html_core: 0.10.1
  fwfh_svg: 0.8.0+2
  fwfh_cached_network_image: 0.7.0+5
  fwfh_url_launcher: 0.9.0+2
#  fwfh_chewie: 0.7.1+2 # accentColor issue
  fwfh_webview: 0.7.0+2
  fwfh_text_style: 2.23.8

  # VIDEO
  video_player: 2.8.5
  youtube_player_iframe: 4.0.4

  # MAP
  google_maps_flutter: 2.2.6
  geocode: 1.0.3
  location: 4.4.0

  # AUTHENTICATION
  local_auth: 2.3.0
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 6.0.1
  google_sign_in: 6.1.0
  sms_autofill: 2.3.0
  permission_handler: 10.2.0

  # FILES, IMAGES
  file_picker: 8.1.2
  cached_network_image: 3.3.1
  image: 4.0.17
  transparent_image: 2.0.1
  image_picker: 0.8.7+5
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.3.1
  wechat_assets_picker: 9.2.2
  photo_manager: 3.0.0

  # TOOLS
  google_fonts: 5.1.0
  random_string: 2.3.1
  json_annotation: 4.8.1
  freezed_annotation: 2.2.0
  timeago: 3.7.0 # depend on intl
  universal_platform: 1.0.0+1
  uuid: 3.0.7
  easy_debounce: 2.0.3
  devicelocale: 0.6.0
  visibility_detector: 0.3.3 # depend on google ads
  rate_my_app: 2.0.0
  flutter_linkify: ^6.0.0
  gms_check: 1.0.1
  google_mobile_ads: 3.0.0
  speech_to_text: 6.1.1

  # UI
  flutter_spinkit: 5.2.0
  smooth_page_indicator: 1.1.0
  animated_text_kit: 4.2.2
  flash: 3.0.5+1
  flutter_staggered_grid_view: 0.6.2
  pin_code_fields: 7.4.0
  country_pickers: 2.0.0
  dropdown_search: 5.0.6
  archive: ^3.6.1
  intro_slider: 4.2.0
  extended_image: 8.2.4
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  qr_code_scanner: 1.0.1
  flutter_calendar_carousel: 2.4.4 # use intl 0.18.0
  sticky_headers: 0.3.0+2
  jumping_dot: 0.0.6
  fl_chart: 0.62.0
  tiktoklikescroller: 0.2.3
  readmore: 2.2.0
  flutter_animate: 4.1.1+1
  flutter_async_autocomplete: 0.1.1
  scrollable_positioned_list: 0.3.8
  country_code_picker: 3.0.0
  flutter_zoom_drawer: 3.0.4+1
  carousel_slider: 5.0.0
  ### Native Payment
#  razorpay_flutter:
#    git:
#      url: https://github.com/inspireui/razorpay-flutter
#      ref: b5b7f1497e9581aadb60cdd00824e8a5747bb03a
  paytm_allinonesdk: 1.2.1
  pay_with_paystack:
    git:
      url: https://github.com/inspireui/pay_with_paystack
      ref: fb5141964b99deb463789433be9ba923770bf58c
  flutter_paystack:
    git:
      url: https://github.com/inspireui/flutter_paystack
      ref: a2f084e96998135ba2f05165887d0750f79852c8
  flutterwave_standard:
    git:
      url: https://github.com/inspireui/Flutterwave
      ref: develop


  #### For Shopify GraphQL
  graphql: 5.2.0-beta.5

  ### Flutter 3 fix warning
  intl_phone_number_input: # custom feature for phone number
    git: https://github.com/inspireui/intl_phone_number_input
  flutter_swiper_null_safety:
    git: https://github.com/inspireui/flutter_swiper_null_safety
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  pull_to_refresh:
    git: https://github.com/inspireui/flutter_pulltorefresh
  new_version_plus: ^0.0.11

  responsive_builder: # hot fix for Flutter 3.10.1
    git:
      url: https://github.com/FilledStacks/responsive_builder
      ref: 876876d6977b9327db0b3bb906747a02bb64b790
  multiple_localization:
    git:
      url: https://github.com/inspireui/flutter_multiple_localization
      ref: 48b65fa88ed468331d56ee86a102d808596c0a50
  app_links: ^6.0.2
  

  ###---- Some extra feature is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.1

  ### â¬‡ï¸ Enable In App Update on Android feature
  ### Uncomment file lib/common/tools/in_app_update_for_android.dart
  #  in_app_update: 4.0.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_native_splash: ^2.3.1
  build_runner: 2.4.4
  freezed: ^2.3.4
  json_serializable: 6.7.0

### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: 3.2.2  # pub run dependency_validator

### Enable Generate Icon library
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/inspireui/flutter_launcher_icons.git
  #     ref: master

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/map_styles/
    - assets/html/
    - google_fonts/

### Uncomment to use custom font
#  fonts:
#    - family: Your Custom Font
#      fonts:
#      - asset: google_fonts/GE-Hili-Book.ttf

flutter_intl:
  enabled: true
  use_deferred_loading: true